site_name: Pygsuite Documentation
repo_url: https://github.com/greenmtnboy/pygsuite
repo_name: pygsuite
docs_dir: docs
pages:
  - Overview: index.md
  - Goals: goals.md
  - Features: features.md
  - Quickstart:
      - Auth: quickstart/auth.md
      - Docs: quickstart/docs.md
      - Sheets: quickstart/sheets.md
      - Slides: quickstart/slides.md
  - Examples:
      - Docs: ref_examples/docs.md
      - Sheets: ref_examples/sheets.md
      - Slides: ref_examples/slides.md
  - Reference:
      - Slides:
          - Images: reference/slides/images.md
          - Lines: references/slides/lines.md
          - Objects: references/slides/objects.md
theme:
  name: material
  palette:
    primary: indigo
    accent: cyan
  font:
    text: Lato
#google_analytics:
#  - "auto"
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true

#  - pymdownx.emoji:
#      emoji_index: !!python/name:pymdownx.emoji.twemoji
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg


