site_name: Pygsuite Documentation
repo_url: https://github.com/greenmtnboy/pygsuite
repo_name: pygsuite
docs_dir: docs
pages:
  - Overview: index.md
  - Goals: goals.md
  - Features: features.md
  - Quickstart:
      - Auth: quickstart/auth.md
      - Docs: quickstart/docs.md
      - Sheets: quickstart/sheets.md
      - Slides: quickstart/slides.md
  - Examples:
      - Docs: ref_examples/docs.md
      - Sheets: ref_examples/sheets.md
      - Slides: ref_examples/slides.md
theme: material
#google_analytics:
#  - "auto"
markdown_extensions:
  - codehilite
  - admonition

